services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
      - ./portainer_logs:/portainer_logs
    environment:
      - LOG_LEVEL=info
      - LOGS_LOCATION=/portainer_logs/portainer.log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - traefik
    ports:
      - 9000:9000
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.portainer.entrypoints=https
        - traefik.http.routers.portainer.rule=Host(`your.domain.com`)
        - traefik.http.routers.portainer.tls.certresolver=letsEncrypt
        - traefik.http.services.portainer.loadbalancer.server.port=9000
      mode: replicated
      placement:
        constraints:
          - "node.labels.TAG==master"

volumes:
  portainer_data:
    driver: local

networks:
  traefik:
    name: traefik
    external: true